# Generated by Django 3.0.6 on 2020-05-30 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import homestay.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('about_area', models.TextField(max_length=1000)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Create date')),
                ('checkin_date', models.DateField(verbose_name='Check in')),
                ('checkout_date', models.DateField(verbose_name='Check out')),
                ('state', models.SmallIntegerField(choices=[(1, 'Just create'), (2, 'confirmed/deposited'), (3, 'Operational'), (0, 'Completed'), (-1, 'Canceled Before Confirm'), (-2, 'Canceled After Confirm'), (-3, 'Noshow')], verbose_name='state')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_area_facility', models.BooleanField(default=False)),
                ('is_character', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Homestay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.TextField(max_length=1000)),
                ('welcomes', models.PositiveSmallIntegerField(default=31, validators=[homestay.models.validator_welcome_value])),
                ('homestay_dot_com_id', models.PositiveIntegerField(null=True, unique=True)),
                ('light_breakfast', models.BooleanField(verbose_name='Complimentary Light Breakfast')),
                ('use_of_kitchen', models.BooleanField(verbose_name='Use of Kitchen')),
                ('rules', models.TextField(max_length=1000, verbose_name='House rules')),
                ('score', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homestay.Address')),
                ('facilities', models.ManyToManyField(to='homestay.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='image/mysite/')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('first_save', models.DateTimeField(auto_now_add=True, null=True)),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.Homestay')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.SmallIntegerField(verbose_name='Overall')),
                ('facility', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Terrific')], verbose_name='Facility')),
                ('cleanliness', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Terrific')], verbose_name='Cleanliness')),
                ('comfort', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Terrific')], verbose_name='Comfort')),
                ('location', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Terrific')], verbose_name='Location')),
                ('valueformoney', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Terrific')], verbose_name='Value For Money')),
                ('feedback', models.TextField(max_length=1000, verbose_name='Feedback')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homestay.Contract', verbose_name='Contract')),
                ('homestay_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homestay.Homestay', verbose_name='Homestay')),
            ],
        ),
    ]
