# Generated by Django 3.0.3 on 2020-04-29 14:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import homestay.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('about_area', models.TextField(max_length=1000)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'unique_together': {('lat', 'lng')},
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_area_facility', models.BooleanField(default=False)),
                ('is_character', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Homestay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.TextField(max_length=1000)),
                ('welcomes', models.PositiveSmallIntegerField(default=31, validators=[homestay.models.validator_welcome_value])),
                ('homestay_dot_com_id', models.PositiveIntegerField(null=True, unique=True)),
                ('light_breakfast', models.BooleanField(verbose_name='Complimentary Light Breakfast')),
                ('use_of_kitchen', models.BooleanField(verbose_name='Use of Kitchen')),
                ('rules', models.TextField(max_length=1000, verbose_name='House rules')),
                ('score', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homestay.Address')),
                ('facilities', models.ManyToManyField(to='homestay.Facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='image/mysite/')),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.Homestay')),
            ],
        ),
    ]
