# Generated by Django 3.0.6 on 2020-05-30 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homestay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='contract',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.GuestInfo', verbose_name='Guest'),
        ),
        migrations.AddField(
            model_name='contract',
            name='homestay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.Homestay', verbose_name='Homestay'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('lat', 'lng')},
        ),
    ]
