# Generated by Django 3.0.3 on 2020-04-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
