# Generated by Django 3.0.3 on 2020-04-30 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0002_reviewimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='first_save',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 14, 17, 4, 799407, tzinfo=utc), null=True),
        ),
    ]
