# Generated by Django 3.0.6 on 2020-06-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0003_auto_20200610_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
