# Generated by Django 3.0.3 on 2020-05-03 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0004_auto_20200501_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='first_save',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 3, 24, 51, 677561, tzinfo=utc), null=True),
        ),
    ]
