# Generated by Django 3.0.3 on 2020-05-04 02:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homestay', '0005_auto_20200503_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='first_save',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 2, 44, 54, 149034, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='Contrast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Create date')),
                ('checkin_date', models.DateTimeField(verbose_name='Check in')),
                ('checkout_date', models.DateTimeField(verbose_name='Check out')),
                ('state', models.SmallIntegerField(choices=[(1, 'Just create'), (2, 'confirmed/deposited'), (3, 'Operational'), (0, 'Completed'), (-1, 'Canceled Before Confirm'), (-2, 'Canceled After Confirm'), (-3, 'Noshow')], verbose_name='state')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Guest')),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.Homestay', verbose_name='Homestay')),
            ],
        ),
    ]
