# Generated by Django 3.0.3 on 2020-05-08 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homestay', '0008_auto_20200504_0650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contrast',
            new_name='Contract',
        ),
    ]
