# Generated by Django 3.0.3 on 2020-05-20 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0009_auto_20200508_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.SmallIntegerField(verbose_name='Overall')),
                ('facility', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Terrific')], verbose_name='Facility')),
                ('cleanliness', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Terrific')], verbose_name='Cleanliness')),
                ('comfort', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Terrific')], verbose_name='Comfort')),
                ('location', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Terrific')], verbose_name='Location')),
                ('valueformoney', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Terrific')], verbose_name='Value For Money')),
                ('feedback', models.TextField(max_length=1000, verbose_name='Feedback')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homestay.Contract', verbose_name='Contract')),
                ('homestay_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homestay.Homestay', verbose_name='Homestay')),
            ],
        ),
    ]
