# Generated by Django 3.0.3 on 2020-04-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomestayManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(unique=True, upload_to='image/mysite/'),
        ),
    ]
